output_path = "/tmp/"
random_seed = 11
target_yield = 186024839
working_pore_percent = 85

[parameters]
experiment_name = "icarust_paper_data"
sample_name = "control_icarust_R9"
flowcell_name = "FAWFAKE3"
experiment_duration_set = 6000
device_id = "FAKE_MINION"
position = "MS00000"
break_read_ms = 1000

[[sample]]
name = "humanHG38"
weight = 1
input_genome = "/squiggle_arrs/human/"
mean_read_length = 28000
weights_files = ["/squiggle_arrs/human/distributions.json",]
