output_path = "/tmp/"
random_seed = 11
target_yield = 186024839
working_pore_percent = 85
pore_type = "R10"

[parameters]
experiment_name = "icarust_paper_data"
sample_name = "adaptive_icarust_R10"
flowcell_name = "FAWFAKE3"
experiment_duration_set = 6000
device_id = "FAKE_MINION"
position = "MS00000"
break_read_ms = 400

[[sample]]
name = "humanHG38"
weight = 1
input_genome = "/squiggle_arrs/hg38_no_alts.fa"
mean_read_length = 28000
